### ISSUE TITLE
Training Flow

### ISSUE THREAD

**Issue by Scott-che** [YouHuang67/InterFormer#4]
![image](https://github.com/YouHuang67/InterFormer/assets/67545227/b20ce8ec-46af-45fe-97b4-a2ef4c83b637)
In SimpleClick, each image undergoes 1 to 3 iterations. During the iteration for one image, previous outputs and new coordinate features are processed through the entire model each time. In your architecture, previous outputs and new coordinate features are fed into 'Feature Decoding.' Therefore, I believe that during the iteration for one image, the image features from 'Feature Encoding' are reused. 
Is my understanding correct?

**Comment by YouHuang67** [comment]
Yes, you are correct. In the InterFormer architecture, each image undergoes 'Feature Encoding' just once. This encoded feature is repeatedly used for multiple interactions to segment any object within the image. Consequently, the reuse rate of the image features is high, particularly when annotating multiple objects in a single image, leading to significantly enhanced processing efficiency.

Thank you for your interest in our work.
